server:
  port: 9988

spring:
  datasource:
    url: jdbc:mysql://localhost:5432/ms_security?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: usersec
    password: usersec
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: securite-service

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.msqlDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: aeesgs-app
    version: '@project.version@'
